// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zunwbfqxlzqrbajjxlwp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp1bndiZnF4bHpxcmJhamp4bHdwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMzg0NTYsImV4cCI6MjA2MzkxNDQ1Nn0.a-63Xay8gVRLyD5wJKiD7-L-EP_tOm1XDajMiXkxnUY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);